sudo: required

language: android
jdk: oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+
    - google-gdk-license-.+
    
before_install:
    - wget --no-check-certificate https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip -O android-ndk-r13b-linux-x86_64.zip
    - unzip android-ndk-r13b-linux-x86_64.zip > android-ndk-r13b-linux-x86_64.uncompress-log 2>&1
    - export ANDROID_NDK_HOME=$PWD/android-ndk-r13b
    - wget https://github.com/Commit451/android-cmake-installer/releases/download/1.1.0/install-cmake.sh
    - chmod +x install-cmake.sh
    - "./install-cmake.sh"
    - find ${ANDROID_HOME}cmake/*/bin/cmake

script:
  - bash ./gradlew :app:assembleDebug

notifications:
  email:
    - xz4214@gmail.com

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
