sudo: required

language: android
jdk: oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+
    - google-gdk-license-.+
    
before_install:
    - wget http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.bin
    - chmod +x android-ndk-$NDK_VERSION-linux-x86_64.bin
    - ./android-ndk-$NDK_VERSION-linux-x86_64.bin | egrep -v ^Extracting
    - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
    - export PATH=${PATH}:${ANDROID_NDK_HOME}

script:
  - bash ./gradlew :app:assembleDebug

notifications:
  email:
    - xz4214@gmail.com

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
